### ISSUE TITLE
How many Frames Per Second?

### ISSUE THREAD

**Issue by beduffy** [clic-lab/chalet#4]
I was wondering if you had calculated or benchmarked the FPS within this environment?

ai2thor currently is at around 20 FPS for a good CPU+GPU and 1 single thread and that was Unity as well. I wonder if it is similar here because of that reason or?

**Comment by dkmisra** [comment]
Hi @beduffy. With 1920x1080 resolution CHALET runs at 90 Fps. The specs of the machine used to measure the FpS are:

Intel i7-6700k CPU 
16 GB RAM
NVIDIA GeForce GTX970

**Comment by beduffy** [comment]
This is great to hear, thanks for benchmarking this! Closing
