### ISSUE TITLE
Is CHALET still supported?

### ISSUE THREAD

**Issue by AshisGhosh** [clic-lab/chalet#6]
Hi, I'm looking for an environment that does exactly what CHALET offers. A complex environment with many types of simplified interactions (i.e. pick/place/open/close/etc). My goal is to test long horizon task planning. 

Is this project still supported?
If not what has it been superseded by anything?

Thanks!

**Comment by yoavartzi** [comment]
We have no capacity to support CHALET at this point. Sorry. It's available to use for anyone interested, but the effort required is up to the user.
